[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = "0.11.0"
yew = "0.19.3"
yew-router = "0.16.0"
serde = "1.0.145"
wasm-bindgen-futures = "0.4.33"
web-sys = "0.3.60"
reqwest = { version = "0.11", features = ["json"] }
log = "0.4.17"
wasm-logger = "0.2.0"
gloo-worker = "0.2.1"
gloo = "0.8.0"
console_error_panic_hook = "0.1.7"
validator = { path = "../validator" }
yew_icons = { version = "0.6.1", features = ["heroicons_solid", "heroicons_outline"] }
