version: '3'

tasks:
  build:
    desc: build the client to wasm
    cmds:
      - trunk clean
      - trunk build

  build:release:
    desc: build the client to wasm in release mode
    cmds:
      - pnpm i
      - trunk clean
      - task: gen:css:raw
      - trunk build --release --dist ../../target/release/client ./index.prod.html

  run:dev:
    desc: run client in dev mode
    deps:
      - task: serve
      - task: gen:css:watch

  serve:
    cmds:
      - trunk serve --open

  gen:css:raw:
    env:
      NODE_ENV: production
    cmds:
      - npx tailwindcss -c ./tailwind.config.js -i ./src/css/input.css -o ./src/css/tailwind.css --minify

  gen:css:
    env:
      NODE_ENV: production
    sources:
      - ./src/**/*.rs
      - ./index.html
      - ./src/**/*.html
      - ./src/**/*.css
    cmds:
      - task: gen:css:raw

  gen:css:watch:
    cmds:
      - task --watch "gen:css"
