version: '3'

tasks:
  build:
    desc: build the client to wasm
    cmds:
      - trunk clean
      - trunk build

  build:release:
    desc: build the client to wasm in release mode
    cmds:
      - trunk clean
      - trunk build --release

  run:dev:
    desc: run client in dev mode
    deps:
      - task: serve

  serve:
    cmds:
      - trunk serve --open

  gen:css:
    env:
      NODE_ENV: production
    sources:
      - ./src/**/*.rs
      - ./index.html
      - ./src/**/*.html
      - ./src/**/*.css
    cmds:
      - tailwindcss -c ./tailwind.config.js -i ./src/css/input.css -o ./src/css/tailwind.css --minify --watch

  gen:css:watch:
    cmds:
      - task --watch "gen:css"
