[workspace]

members = [
  "packages/server",
  "packages/entity",
  "packages/migration",
  "packages/client",
  "packages/field-names",
  "packages/validator"
]

default-members = ["packages/server"]
