version: "3.8"

services:

  pg:
    image: "postgres:14.4-alpine3.16"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: rust_todo_wasm
    ports:
      - 5449:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      CLIENT_DIR: ../client
      DATABASE_URL: postgres://pguser:pgpass@pg/rust_todo_wasm
      JWT_SECRET: McI6A9!kEgz81v^%f%vVx8mzKS
      SALT: o#596T*O65MATwDX4LtR
      API_URL: ""
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - pg

volumes:
  pg-data:
