version: '3'

includes:
  server:
    taskfile: ./packages/server
    dir: ./packages/server
  client:
    taskfile: ./packages/client
    dir: ./packages/client

env:
  DATABASE_URL: postgres://pguser:pgpass@127.0.0.1:5449/rust_todo_wasm
  RUST_LOG: debug
  JWT_SECRET: McI6A9!kEgz81v^%f%vVx8mzKS
  SALT: o#596T*O65MATwDX4LtR

tasks:
  init:
    desc: init the project
    cmds:
      - rustup target add wasm32-unknown-unknown
      - cargo install trunk
      - cargo install cargo-watch
      - cargo install sea-orm-cli

  check:
    desc: check applications
    cmds:
      - cargo check --all

  test:
    desc: test applications
    cmds:
      - cargo test --all

  lint:
    desc: lint applications
    cmds:
      - cargo clippy --all

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo +nightly fmt --all

  graphql:gen:
    desc: generate graphql server thanks to seaography
    cmds:
      - seaography-cli $DATABASE_URL ./packages/seaography-example