version: '3'

includes:
  server:
    taskfile: ./packages/server
    dir: ./packages/server
  client:
    taskfile: ./packages/client
    dir: ./packages/client

dotenv: ['.env']

tasks:
  init:
    desc: init the project
    cmds:
      - cargo install trunk
      - cargo install cargo-watch
      - cargo install sea-orm-cli
      - rustup target add wasm32-unknown-unknown

  up:
    desc: run docker-compose with buildkit enabled
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    cmds:
      - docker-compose up -d

  build:release:
    desc: build production application
    env:
      API_URL: ""
    cmds:
      - cargo build --release
      - task: client:build:release

  run:dev:
    desc: run project in development environment
    env:
      RUST_ENV: development
    deps:
      - task: server:run:dev
      - task: client:run:dev

  check:
    desc: check applications
    cmds:
      - cargo check --all

  test:
    desc: test applications
    cmds:
      - cargo test --all

  lint:
    desc: lint applications
    cmds:
      - cargo clippy --all

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo +nightly fmt --all

  graphql:gen:
    desc: generate graphql server thanks to seaography
    cmds:
      - seaography-cli $DATABASE_URL ./packages/seaography-example

  fix:all:
    desc: fill format and lint issues when it is possible
    cmds:
      - task: format
      - task: lint:fix

  migration:gen:
    desc: generate new migration
    env:
      name:
    cmds:
      - sea-orm-cli migrate generate -d ./packages/migration {{.name}}
