version: '3'

includes:
  server:
    taskfile: ./packages/server
    dir: ./packages/server
  client:
    taskfile: ./packages/client
    dir: ./packages/client

env:
  DATABASE_URL: postgres://pguser:pgpass@127.0.0.1:5449/rust_todo_wasm
  RUST_LOG: debug
  JWT_SECRET: McI6A9!kEgz81v^%f%vVx8mzKS
  SALT: o#596T*O65MATwDX4LtR
  API_URL: http://127.0.0.1:3000

tasks:
  init:
    desc: init the project
    cmds:
      - cargo install trunk
      - cargo install cargo-watch
      - cargo install sea-orm-cli
      - rustup target add wasm32-unknown-unknown

  build:release:
    desc: build production application
    env:
      API_URL: ""
    cmds:
      - cargo build --release
      - task: client:build:release

  run:dev:
    desc: run project in development environment
    deps:
      - task: server:run:dev
      - task: client:run:dev

  check:
    desc: check applications
    cmds:
      - cargo check --all

  test:
    desc: test applications
    cmds:
      - cargo test --all

  lint:
    desc: lint applications
    cmds:
      - cargo clippy --all

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo +nightly fmt --all

  graphql:gen:
    desc: generate graphql server thanks to seaography
    cmds:
      - seaography-cli $DATABASE_URL ./packages/seaography-example

  fix:all:
    desc: fill format and lint issues when it is possible
    cmds:
      - task: format
      - task: lint:fix
