[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal packages
entity = { path = "../entity" }
migration = { path = "../migration" }

# external packages
async-graphql = { version = "4.0.14", features = ["uuid08"] }
async-graphql-axum = "4.0.14"
axum = "0.5.16"
axum-extra = { version = "0.3.7", features = ["spa"] }
log = "0.4.17"
once_cell = "1.15.0"
sea-orm = { version = "0.9.3", features = ["sqlx-postgres", "runtime-tokio-native-tls"] }
serde = "1.0.145"
tokio = { version = "1.21.1", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
uuid = "1.1.2"
thiserror = "1.0.37"
http = "0.2.8"

