version: '3'

tasks:
  run:dev:
    desc: run server in development mode
    cmds:
      - cargo-watch -x run

  build:
    desc: build the server
    cmds:
      - cargo build

  build:release:
    desc: build the server in release mode
    cmds:
      - cargo build --release

