[package]
name = "field-names"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
darling = "0.14.1"
proc-macro2 = "1.0.46"
quote = "1.0.21"
syn = { version = "1.0", features = ["full"] }
