name: rust

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            target: wasm32-unknown-unknown
        - name: check format
          run: cargo check --all
        - name: check lint
          run: cargo clippy --all
        - name: run tests
          run: cargo test --all
