name: tests

on:
  workflow_run:
    workflows: [build]
    types:
      - completed

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            restore_keys: |
              ${{ runner.os }}-cargo-
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            target: wasm32-unknown-unknown
        - name: check format
          run: cargo check --all
        - name: check lint
          run: cargo clippy --all
        - name: run tests
          run: cargo test --all
